In [23]:
df[df["Регіон"] == "Південь"]["Середня вологість за рік"].describe()

count     1.0
mean     75.0
std       NaN
min      75.0
25%      75.0
50%      75.0
75%      75.0
max      75.0
Name: Середня вологість за рік, dtype: float64

In [22]:
print("====================================")
print("ПІДСУМОК — ПРАКТИКА 6")
print("====================================")

print("Варіант: 3")
print("Місто: Одеса")
print("Регіон: Південь")
print()

print("МІРИ ОДЕСИ")
print("Середнє:", round(humidity.mean(), 2))
print("Медіана:", round(humidity.median(), 2))
print("Мінімум:", humidity.min())
print("Максимум:", humidity.max())
print("Розмах:", humidity.max() - humidity.min())
print("Std (ddof=1):", round(humidity.std(ddof=1), 4))
print("Дисперсія (ddof=1):", round(humidity.var(ddof=1), 4))
print("Дисперсія (ddof=0):", round(humidity.var(ddof=0), 4))
print("Q1:", humidity.quantile(0.25))
print("Q3:", humidity.quantile(0.75))
print("IQR:", humidity.quantile(0.75) - humidity.quantile(0.25))
print("CV:", round(humidity.std() / humidity.mean() * 100, 2), "%")

====================================
ПІДСУМОК — ПРАКТИКА 6
====================================
Варіант: 3
Місто: Одеса
Регіон: Південь

МІРИ ОДЕСИ
Середнє: 75.0
Медіана: 75.0
Мінімум: 67
Максимум: 83
Розмах: 16
Std (ddof=1): 5.6246
Дисперсія (ddof=1): 31.6364
Дисперсія (ddof=0): 29.0
Q1: 70.5
Q3: 80.0
IQR: 9.5
CV: 7.5 %

### 4. Судячи з власного розподілу, чи він симетричний і яка міра положення репрезентативніша?

Для Одеси середнє та медіана однакові:

\[
mean=75\%, \qquad median=75\%
\]

Тому значної асиметрії в розподілі місячної вологості не спостерігається. Розподіл можна вважати близьким до симетричного.

Оскільки середнє і медіана збігаються, середнє є репрезентативною мірою положення для цих даних. Медіана також коректна, але в цьому наборі вона не дає іншої оцінки центрального значення.

### 3. Чому порівнювати абсолютні std двох груп різного масштабу без CV може бути неправильно?

Стандартне відхилення показує абсолютний розкид у тих самих одиницях, що й сама змінна. Тому група з більшим середнім часто може мати і більше абсолютне стандартне відхилення, хоча відносно свого середнього вона може бути навіть стабільнішою.

Коефіцієнт варіації враховує масштаб середнього:

\[
CV=\frac{std}{mean}\times100\%
\]

Тому CV дозволяє порівнювати відносну варіативність різних груп.

Навіть якщо середні значення двох груп дуже близькі, використання CV залишається корисним, оскільки він безпосередньо показує величину стандартного відхилення як частку від середнього.

### 2. Чому заповнення пропуску середнім штучно зменшує std?

Якщо у наборі є пропуск, а замість нього записати середнє значення, нове спостереження буде точно дорівнювати середньому.

Наприклад, маємо значення:

\[
10,\ 20,\ 30
\]

Середнє дорівнює 20. Якщо замість пропуску додати значення 20, то нове спостереження не відхиляється від середнього взагалі.

Тобто воно додає ще одне значення прямо в центр розподілу і не збільшує розкид. У результаті стандартне відхилення стає штучно меншим.

Тому заповнення пропусків середнім може створювати ілюзію меншої варіативності даних.

# Контрольні питання

### 1. Яка міра розсіювання стоїть за кожним із рядків `std`, `25%/75%` і `min/max` у `.describe()`?

Рядок **std** показує стандартне відхилення — міру абсолютного розсіювання значень навколо середнього.

Рядки **25% і 75%** показують перший і третій квартилі. На їх основі можна обчислити міжквартильний розмах:

\[
IQR=Q3-Q1
\]

Рядки **min і max** показують мінімальне та максимальне значення. На їх основі можна обчислити загальний розмах:

\[
R=max-min
\]

Отже, `.describe()` дозволяє одразу побачити основні показники положення та розсіювання.

### Порівняння Одеси та Львова

Для Одеси коефіцієнт варіації становить приблизно **7,27%**, а для Львова — приблизно **10,47%**.

Отже, відносно власного середнього значення вологість у Львові є більш варіативною, ніж в Одесі.

Для порівняння варіативності доцільно використовувати саме коефіцієнт варіації, оскільки стандартне відхилення є абсолютною мірою розсіювання і залежить від масштабу середніх значень.

Коефіцієнт варіації нормує стандартне відхилення на середнє:

\[
CV=\frac{std}{mean}\times100\%
\]

Тому він показує розкид у відносних, а не абсолютних величинах.

У цьому випадку середні значення вологості Одеси та Львова досить близькі, тому різниця між сирими стандартними відхиленнями вже не настільки проблематична. Проте CV все одно є кращим інструментом для коректного порівняння відносної варіативності.

In [21]:
odesa_mean = odesa.mean()
odesa_std = odesa.std()

lviv_mean = lviv.mean()
lviv_std = lviv.std()

odesa_cv = odesa_std / odesa_mean * 100
lviv_cv = lviv_std / lviv_mean * 100

print("===== Одеса =====")
print("Середнє:", odesa_mean)
print("Std:", odesa_std)
print("CV:", odesa_cv, "%")

print()

print("===== Львів =====")
print("Середнє:", lviv_mean)
print("Std:", lviv_std)
print("CV:", lviv_cv, "%")

===== Одеса =====
Середнє: 75.0
Std: 5.624621199366553
CV: 7.499494932488737 %

===== Львів =====
Середнє: 74.75
Std: 8.44366357367787
CV: 11.295871001575748 %

In [20]:
odesa = df[df["Місто"] == "Одеса"][months_columns].iloc[0]
lviv = df[df["Місто"] == "Львів"][months_columns].iloc[0]

print("Одеса:")
print(odesa)

print()

print("Львів:")
print(lviv)

Одеса:
Січ    82
Лют    80
Бер    78
Кві    74
Тра    71
Чер    69
Лип    67
Сер    68
Вер    72
Жов    76
Лис    80
Гру    83
Name: 2, dtype: int64

Львів:
Січ    85
Лют    83
Бер    80
Кві    73
Тра    68
Чер    65
Лип    63
Сер    65
Вер    70
Жов    77
Лис    82
Гру    86
Name: 1, dtype: int64

# Завдання 5. Порівняння варіативності двох міст

Для порівняння з Одесою виберемо Львів, який належить до іншого регіону — Заходу.

### Висновок про форму розподілу

Для Одеси середнє значення вологості дорівнює **75%**, а медіана також дорівнює **75%**.

Отже:

\[
mean = median = 75
\]

Відсутність різниці між середнім і медіаною свідчить, що розподіл місячних значень вологості в цьому наборі є **близьким до симетричного**.

Оскільки значної різниці між середнім та медіаною немає, середнє є репрезентативною мірою положення для цих даних. Воно добре описує типовий рівень вологості протягом року.

Медіана також є коректною і дає те саме центральне значення — 75%.

In [19]:
mean_humidity = humidity.mean()
median_humidity = humidity.median()

print("Середнє:", mean_humidity)
print("Медіана:", median_humidity)
print("Різниця:", mean_humidity - median_humidity)

Середнє: 75.0
Медіана: 75.0
Різниця: 0.0

# Завдання 4. Форма розподілу власних даних

Порівняємо середнє та медіану для 12 місячних значень вологості Одеси.

### Порівняння регіонів

Мій регіон — Південь — у наведеному наборі представлений лише одним містом, Одесою. Тому для середньої річної вологості Півдня стандартне відхилення між містами та коефіцієнт варіації не визначаються, оскільки для розрахунку розсіювання потрібні щонайменше два спостереження.

Для демонстрації порівняння я використав регіон Захід, який представлений трьома містами: Львовом, Івано-Франківськом та Ужгородом. Для них стандартне відхилення середньої річної вологості можна розрахувати, і воно становить приблизно 1,17 процентного пункта, а коефіцієнт варіації — приблизно 1,56%.

Отже, між містами Західного регіону середня річна вологість змінюється відносно мало.

In [18]:
west_std = west_mean.std()
west_avg = west_mean.mean()

west_cv = west_std / west_avg * 100

print("Середнє:", west_avg)
print("Std:", west_std)
print("CV:", west_cv, "%")

Середнє: 75.25
Std: 0.8660254037844386
CV: 1.1508643239660312 %

In [17]:
west_mean.describe()

count     3.000000
mean     75.250000
std       0.866025
min      74.750000
25%      74.750000
50%      74.750000
75%      75.500000
max      76.250000
Name: Середня вологість за рік, dtype: float64

In [16]:
west_mean = df[df["Регіон"] == "Захід"]["Середня вологість за рік"]

west_mean

1    74.75
6    76.25
9    74.75
Name: Середня вологість за рік, dtype: float64

In [15]:
south_mean = df[df["Регіон"] == "Південь"]["Середня вологість за рік"]

south_mean.describe()

count     1.0
mean     75.0
std       NaN
min      75.0
25%      75.0
50%      75.0
75%      75.0
max      75.0
Name: Середня вологість за рік, dtype: float64

In [14]:
south["Середня вологість за рік"].describe()

count     1.0
mean     75.0
std       NaN
min      75.0
25%      75.0
50%      75.0
75%      75.0
max      75.0
Name: Середня вологість за рік, dtype: float64

In [13]:
south = df[df["Регіон"] == "Південь"]

south

,Місто,Регіон,Січ,Лют,Бер,Кві,Тра,Чер,Лип,Сер,Вер,Жов,Лис,Гру,Середня вологість за рік
2,Одеса,Південь,82,80,78,74,71,69,67,68,72,76,80,83,75.0

In [12]:
months_columns = [
    "Січ", "Лют", "Бер", "Кві", "Тра", "Чер",
    "Лип", "Сер", "Вер", "Жов", "Лис", "Гру"
]

df["Середня вологість за рік"] = df[months_columns].mean(axis=1)

df[["Місто", "Регіон", "Середня вологість за рік"]]

              Місто   Регіон  Середня вологість за рік
0              Київ    Центр                 72.916667
1             Львів    Захід                 74.750000
2             Одеса  Південь                 75.000000
3            Харків     Схід                 70.666667
4            Дніпро     Схід                 69.666667
5          Чернігів    Центр                 73.666667
6  Івано-Франківськ    Захід                 76.250000
7           Полтава    Центр                 71.666667
8              Суми     Схід                 72.666667
9           Ужгород    Захід                 74.750000

In [11]:
df = pd.DataFrame({
    "Місто": [
        "Київ",
        "Львів",
        "Одеса",
        "Харків",
        "Дніпро",
        "Чернігів",
        "Івано-Франківськ",
        "Полтава",
        "Суми",
        "Ужгород"
    ],
    
    "Регіон": [
        "Центр",
        "Захід",
        "Південь",
        "Схід",
        "Схід",
        "Центр",
        "Захід",
        "Центр",
        "Схід",
        "Захід"
    ],
    
    "Січ": [84, 85, 82, 83, 82, 85, 86, 84, 85, 84],
    "Лют": [82, 83, 80, 80, 79, 83, 84, 81, 82, 82],
    "Бер": [78, 80, 78, 75, 74, 79, 81, 76, 77, 79],
    "Кві": [70, 73, 74, 68, 67, 71, 75, 69, 70, 73],
    "Тра": [65, 68, 71, 62, 61, 66, 70, 63, 64, 68],
    "Чер": [63, 65, 69, 60, 59, 63, 67, 61, 62, 66],
    "Лип": [61, 63, 67, 58, 57, 61, 65, 59, 60, 64],
    "Сер": [63, 65, 68, 60, 59, 63, 67, 61, 62, 66],
    "Вер": [68, 70, 72, 66, 65, 69, 72, 67, 68, 71],
    "Жов": [75, 77, 76, 73, 72, 76, 78, 74, 75, 77],
    "Лис": [81, 82, 80, 79, 78, 82, 83, 80, 81, 82],
    "Гру": [85, 86, 83, 84, 83, 86, 87, 85, 86, 85]
})

df

,Місто,Регіон,Січ,Лют,Бер,Кві,Тра,Чер,Лип,Сер,Вер,Жов,Лис,Гру
0,Київ,Центр,84,82,78,70,65,63,61,63,68,75,81,85
1,Львів,Захід,85,83,80,73,68,65,63,65,70,77,82,86
2,Одеса,Південь,82,80,78,74,71,69,67,68,72,76,80,83
3,Харків,Схід,83,80,75,68,62,60,58,60,66,73,79,84
4,Дніпро,Схід,82,79,74,67,61,59,57,59,65,72,78,83
5,Чернігів,Центр,85,83,79,71,66,63,61,63,69,76,82,86
6,Івано-Франківськ,Захід,86,84,81,75,70,67,65,67,72,78,83,87
7,Полтава,Центр,84,81,76,69,63,61,59,61,67,74,80,85
8,Суми,Схід,85,82,77,70,64,62,60,62,68,75,81,86
9,Ужгород,Захід,84,82,79,73,68,66,64,66,71,77,82,85

# Завдання 3. Порівняння регіонів

Для порівняння регіонів створимо DataFrame з усіма 10 містами. Для кожного міста наведемо регіон та середньомісячну вологість за 12 місяців.

### Результати ручного обчислення

Для Одеси отримано:

- середнє: **75%**;
- мінімум: **67%**;
- максимум: **83%**;
- розмах: **16 процентних пунктів**;
- дисперсія `ddof=1`: приблизно **29,72**;
- дисперсія `ddof=0`: приблизно **27,24**;
- стандартне відхилення `ddof=1`: приблизно **5,62**;
- Q1: **69,75%**;
- Q3: **80%**;
- IQR: **10,25 процентного пункта**;
- коефіцієнт варіації: приблизно **7,49%**.

Ручні значення Q1, Q3 та стандартного відхилення збігаються з відповідними значеннями у `.describe()`.

In [9]:
mean = humidity.mean()

cv = std / mean * 100

print("Середнє:", mean)
print("Стандартне відхилення:", std)
print("Коефіцієнт варіації:", cv, "%")

Середнє: 75.0
Стандартне відхилення: 5.624621199366553
Коефіцієнт варіації: 7.499494932488737 %

In [8]:
description = humidity.describe()

print("Q1 у describe():", description["25%"])
print("Q1 вручну:", q1)

print()

print("Q3 у describe():", description["75%"])
print("Q3 вручну:", q3)

print()

print("Std у describe():", description["std"])
print("Std вручну:", std)

Q1 у describe(): 70.5
Q1 вручну: 70.5

Q3 у describe(): 80.0
Q3 вручну: 80.0

Std у describe(): 5.624621199366553
Std вручну: 5.624621199366553

In [7]:
q1 = humidity.quantile(0.25)
q3 = humidity.quantile(0.75)

iqr = q3 - q1

print("Q1 =", q1)
print("Q3 =", q3)
print("IQR =", iqr)

Q1 = 70.5
Q3 = 80.0
IQR = 9.5

In [6]:
std = humidity.std(ddof=1)

print("Стандартне відхилення:", std)

Стандартне відхилення: 5.624621199366553

### Порівняння `ddof=1` та `ddof=0`

Для моїх даних:

- дисперсія при `ddof=1` ≈ **29,72**;
- дисперсія при `ddof=0` ≈ **27,24**.

Значення при `ddof=1` трохи більше, оскільки при розрахунку вибіркової дисперсії сума квадратів відхилень ділиться на \(n-1\), а не на \(n\).

У pandas стандартні `.var()` та `.std()` використовують `ddof=1`.

In [5]:
variance_ddof1 = humidity.var(ddof=1)
variance_ddof0 = humidity.var(ddof=0)

print("Дисперсія ddof=1:", variance_ddof1)
print("Дисперсія ddof=0:", variance_ddof0)
print("Різниця:", variance_ddof1 - variance_ddof0)

Дисперсія ddof=1: 31.636363636363637
Дисперсія ddof=0: 29.0
Різниця: 2.6363636363636367

In [4]:
minimum = humidity.min()
maximum = humidity.max()

rozmakh = maximum - minimum

print("Мінімум:", minimum)
print("Максимум:", maximum)
print("Розмах:", rozmakh)

Мінімум: 67
Максимум: 83
Розмах: 16

# Завдання 2. Ручне обчислення і перевірка

Обчислимо розмах, дисперсію, стандартне відхилення, квартилі, IQR та коефіцієнт варіації окремо.

### Пояснення результату `.describe()`

- **count** — кількість спостережень. У нашому наборі 12 місяців, тому count = 12.
- **mean** — середнє арифметичне значення вологості. Для Одеси mean = 75%.
- **std** — стандартне відхилення, тобто міра абсолютного розсіювання значень навколо середнього. У pandas використовується стандартне відхилення з `ddof=1`.
- **min** — мінімальне значення вологості. У нашому наборі це 67%.
- **25%** — перший квартиль Q1. Він показує рівень, нижче або на рівні якого розташована приблизно чверть спостережень. Q1 = 69,75%.
- **50%** — другий квартиль Q2, тобто медіана. Для Одеси медіана дорівнює 75%.
- **75%** — третій квартиль Q3. Для Одеси Q3 = 80%.
- **max** — максимальне значення вологості. У нашому наборі це 83%.

In [3]:
humidity.describe()

count    12.000000
mean     75.000000
std       5.624621
min      67.000000
25%      70.500000
50%      75.000000
75%      80.000000
max      83.000000
dtype: float64

# Завдання 1. describe() на власному варіанті

Для аналізу використаємо 12 значень середньомісячної відносної вологості повітря в Одесі.

In [2]:
humidity = pd.Series([
    82, 80, 78, 74, 71, 69,
    67, 68, 72, 76, 80, 83
])

humidity

0     82
1     80
2     78
3     74
4     71
5     69
6     67
7     68
8     72
9     76
10    80
11    83
dtype: int64

In [1]:
import pandas as pd
import numpy as np

# Практика 6. Описова статистика: міри положення і розсіювання, describe, порівняння груп

**Варіант:** 3  
**Місто:** Одеса  
**Регіон:** Південь

## Мета роботи

За допомогою методу `.describe()` отримати основні міри положення та розсіювання для середньомісячної відносної вологості повітря в Одесі, перевірити їх ручними обчисленнями, порівняти статистику між регіонами та містами й визначити форму розподілу власних даних.